### ISSUE TITLE
Reshuffle lib and include

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/N2-AvionicsFlightSoftware#2]
Follow the C guidelines

Suggested structure:
```
include/
    statemachine/
       statemachine.h
       statemachine.cpp
    kalmanfilter/
       kalmanfilter.h
       kalmanfilter.cpp
```

References:
- [GeeksforGeeks](https://www.geeksforgeeks.org/difference-header-file-library/)

**Comment by ObaraEmmanuel** [comment]
@0x6f736f646f what exactly do you need done, I can separate the header files into .h and .cpp but from the issue description I am not sure if this is all that is needed.

**Comment by rodneyosodo** [comment]
@ObaraEmmanuel `lib` folder is used for actual libraries that can be used by other people. Currently we haven't implemented any library so I suggest moving what is in the `lib` folder to `include` folder since they are internal sought of libraries.

**Comment by rodneyosodo** [comment]
Also seperating `.h` and `.cpp` files would be a good idea

**Comment by rodneyosodo** [comment]
> @ObaraEmmanuel `lib` folder is used for actual libraries that can be used by other people. Currently we haven't implemented any library so I suggest moving what is in the `lib` folder to `include` folder since they are internal sought of libraries.

Actually this is done probably it would be great to separate the `cpp` and `h` files then add them in subdirectories

**Comment by ObaraEmmanuel** [comment]
we could have the `cpp` files inside `src` and leave only the `h` files in `include`

**Comment by kimanimichael** [comment]
@0x6f736f646f Does #4 address this issue completely?

**Comment by ObaraEmmanuel** [comment]
@Mike-Kimani  I think it does because there is nothing in `lib` anyway. As for the suggested structure I think it may be overkill to have a folder for each file. It is also involves putting `.cpp` files inside `include` which should really only contain header files.

**Comment by rodneyosodo** [comment]
Closed with https://github.com/nakujaproject/N2-AvionicsFlightSoftware/commit/53821863662eb70f7275857348590039698a9225
